{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  start.sh: |-
{{ .Files.Get .Values.configMap.startScriptPath | indent 4 }}
{{- end }}
