{{- if .Values.workloadidentity.create -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure  
  parameters:
    {{- toYaml .Values.workloadidentity.parameters | nindent 4 }}               
  secretObjects:
    {{- toYaml .Values.workloadidentity.secretObjects | nindent 4 }}  
{{- end }}