{{- range .Values.basicSettings.secretEnvs }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tomtom-base-chart.fullname" $ }}-{{ .name }}-env-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .secretStore }}
    kind: SecretStore
  target:
    name: {{ .secretName }}
    creationPolicy: Owner
  data:
  {{- range $key, $value := .secrets }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $value }}
  {{- end }}
{{- end }}
{{- range .Values.basicSettings.secretFiles }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tomtom-base-chart.fullname" $ }}-{{ .name }}-file-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .secretStore }}
    kind: SecretStore
  target:
    name: {{ .secretName }}
    creationPolicy: Owner
  data:
  {{- range $key, $value := .secrets }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $value }}
  {{- end }}
{{- end }}
