{{- if .Values.basicSettings.fqdn -}}
{{- $ingressFullName := include "tomtom-base-chart.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $ingressFullName }}-ipallowlist
spec:
  ipWhiteList:
    sourceRange:
    {{- with .Values.basicSettings.allowedIpRanges }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}