{{- if .Values.advancedSettings.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tomtom-base-chart.serviceAccountName" . }}
  labels:
    {{- include "tomtom-base-chart.labels" . | nindent 4 }}
  {{- with .Values.advancedSettings.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
